/*

 BACKGROUND-TILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char background[] =
{
  0xFF,0xFF,0xDB,0xA5,0xBD,0xC3,0xE7,0x91,
  0xE7,0x89,0xBD,0xC3,0xD9,0xA5,0xFF,0xFF,
  0x44,0x21,0x8C,0x73,0x28,0x01,0x81,0x56,
  0x63,0x18,0x2A,0xC4,0x26,0x51,0x50,0x0A
};

/* End of BACKGROUND-TILES.C */
