import sys
sys.setrecursionlimit(100000000)

F = lambda x: lambda y: x
T = lambda x: lambda y: y
logic_not = lambda a: lambda x: lambda y: a(y)(x)
logic_and = lambda a: lambda b: a(F)(b)
logic_or = lambda a: lambda b: a(b)(T)
pair = lambda a: lambda b: lambda z: z(a)(b)
succ = lambda num: lambda f: lambda x: num(f)(f(x)) 
zero = lambda f: lambda x: x
one = succ(zero)
two = succ(one)
three = succ(two)
four = succ(three)
pred = lambda num: num(lambda p: pair(succ(p(F)))(p(F)))(pair(zero)(zero))(T)
add = lambda numA: lambda numB: lambda f: lambda x: numA(f)(numB(f)(x))
sub = lambda numA: lambda numB: numB(pred)(numA)
mult = lambda numA: lambda numB: lambda f: numA(numB(f))
exp = lambda numA: lambda numB: numB(numA)
square = lambda x: mult(x)(x)
iszero = lambda num: num(lambda ign: F)(T)
numeq = lambda numA: lambda numB: logic_and(iszero(sub(numA)(numB)))(iszero(sub(numB)(numA)))
nil = lambda f:lambda x: x
cons = lambda head: lambda tail: lambda f: lambda x: tail(f)(f(head)(x))
numtochurch = lambda num: zero if num==0 else succ(numtochurch(num-1))
listtochurch = lambda l: nil if l==[] else cons(numtochurch(l[-1]))(listtochurch(l[:-1]))
flag = listtochurch([ord(c)-50 for c in input()])
secret = lambda l: lambda x: l(lambda hd:lambda transtl:pair(add(transtl(F))(mult(transtl(T))(hd)))(pred(transtl(T))))(pair(zero)(x))(F)

print(numeq(secret(flag)(one))(add(exp(three)(three))(add(exp(three)(three))(add(exp(four)(two))(add(mult(two)(two))(one)))))(False)(True))
print(numeq(secret(flag)(two))(add(exp(add(mult(two)(three))(one))(two))(add(exp(two)(add(mult(three)(two))(one)))(add(exp(three)(three))(mult(add(mult(two)(two))(one))(two)))))(False)(True))
print(numeq(secret(flag)(three))(add(exp(add(mult(two)(three))(one))(three))(add(mult(two)(add(mult(two)(two))(one)))(one)))(False)(True))
print(numeq(secret(flag)(four))(add(exp(add(mult(two)(four))(one))(two))(add(exp(mult(two)(add(mult(two)(two))(one)))(two))(add(exp(mult(three)(two))(three))(add(exp(three)(four))(add(exp(three)(four))(one))))))(False)(True))
print(numeq(secret(flag)(add(mult(two)(two))(one)))(add(exp(add(mult(three)(two))(one))(three))(add(exp(mult(three)(two))(three))(add(exp(mult(two)(four))(two))(add(exp(add(mult(two)(two))(one))(three))(add(exp(three)(four))(two))))))(False)(True))
print(numeq(secret(flag)(mult(two)(three)))(add(exp(add(mult(two)(three))(one))(three))(add(exp(mult(three)(two))(three))(add(exp(add(mult(four)(two))(one))(two))(add(exp(mult(add(mult(two)(two))(one))(two))(two))(add(exp(add(mult(three)(two))(one))(three))(add(exp(two)(four))(add(mult(two)(two))(one))))))))(False)(True))
print(numeq(secret(flag)(add(mult(three)(two))(one)))(add(exp(mult(three)(two))(four))(add(exp(three)(four))(add(exp(three)(three))(add(exp(three)(three))(add(mult(two)(two))(one))))))(False)(True))
print(numeq(secret(flag)(mult(four)(two)))(add(exp(add(mult(two)(four))(one))(three))(add(exp(mult(four)(two))(three))(add(exp(mult(two)(four))(three))(add(exp(four)(two))(add(exp(four)(two))(add(exp(four)(two))(mult(three)(four))))))))(False)(True))
print(numeq(secret(flag)(add(mult(four)(two))(one)))(add(exp(add(mult(four)(two))(one))(three))(add(exp(mult(three)(two))(four))(add(exp(two)(add(mult(three)(two))(one)))(add(exp(two)(add(mult(two)(two))(one)))(add(mult(two)(three))(one))))))(False)(True))
print(numeq(secret(flag)(add(mult(four)(two))(two)))(add(exp(mult(three)(two))(four))(add(exp(add(mult(two)(three))(one))(three))(add(exp(add(mult(two)(two))(one))(four))(add(exp(add(mult(two)(three))(one))(three))(add(mult(three)(four))(two))))))(False)(True))
print(numeq(secret(flag)(add(mult(three)(three))(two)))(add(exp(add(mult(three)(two))(two))(three))(add(exp(add(mult(two)(two))(one))(four))(add(exp(mult(two)(add(mult(two)(two))(one)))(three))(add(exp(add(mult(three)(three))(one))(two))(add(exp(mult(three)(three))(three))(add(exp(three)(four))(add(exp(two)(add(mult(two)(two))(one)))(add(exp(two)(four))(three)))))))))(False)(True))
print(numeq(secret(flag)(mult(three)(four)))(add(exp(add(mult(two)(three))(one))(four))(add(exp(add(mult(three)(two))(one))(three))(add(exp(add(mult(two)(three))(one))(three))(add(exp(add(mult(two)(two))(one))(three))(add(exp(add(mult(three)(two))(two))(two))(add(exp(mult(three)(three))(two))(add(exp(add(mult(two)(two))(one))(three))(add(exp(two)(add(mult(two)(three))(one)))(add(exp(two)(four))(add(mult(three)(two))(two)))))))))))(False)(True))
print(numeq(secret(flag)(add(mult(add(mult(two)(two))(one))(two))(three)))(add(exp(add(mult(three)(two))(two))(four))(add(exp(three)(three))(add(exp(two)(add(mult(two)(two))(one)))(add(exp(four)(two))(one)))))(False)(True))
print(numeq(secret(flag)(add(mult(add(mult(two)(two))(one))(two))(four)))(add(exp(add(mult(two)(four))(one))(three))(add(exp(add(mult(three)(two))(two))(three))(add(exp(mult(three)(two))(four))(add(exp(mult(two)(add(mult(two)(two))(one)))(three))(add(exp(mult(three)(two))(three))(add(exp(mult(add(mult(two)(two))(one))(two))(three))(mult(three)(add(mult(two)(two))(one)))))))))(False)(True))
print(numeq(secret(flag)(mult(three)(add(mult(two)(two))(one))))(add(exp(add(mult(two)(three))(one))(four))(add(exp(mult(add(mult(two)(two))(one))(two))(three))(add(exp(mult(two)(add(mult(two)(two))(one)))(three))(add(exp(add(mult(four)(two))(one))(three))(add(exp(mult(two)(four))(two))(add(exp(add(mult(four)(two))(one))(two))(add(exp(three)(four))(add(exp(four)(three))(add(exp(three)(two))(mult(four)(two)))))))))))(False)(True))
print(numeq(secret(flag)(add(mult(add(mult(two)(two))(one))(three))(one)))(add(exp(mult(two)(three))(four))(add(exp(mult(four)(two))(four))(add(exp(mult(two)(four))(three))(add(exp(mult(three)(two))(three))(add(mult(two)(mult(three)(two)))(one))))))(False)(True))
print(numeq(secret(flag)(add(exp(two)(four))(one)))(add(exp(add(mult(three)(two))(two))(four))(add(exp(mult(two)(three))(four))(add(exp(mult(three)(two))(four))(add(exp(two)(add(mult(three)(two))(one)))(add(exp(three)(three))(add(exp(two)(four))(three)))))))(False)(True))
print(numeq(secret(flag)(add(exp(two)(four))(two)))(add(exp(mult(three)(three))(four))(add(exp(mult(two)(three))(three))(add(exp(add(mult(four)(two))(one))(three))(add(exp(two)(mult(two)(three)))(add(exp(three)(three))(add(exp(four)(two))(add(mult(four)(two))(three))))))))(False)(True))
